### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by makuser** [ruuvi-friends/ruuvi-hass.io#10]
Hello @sergioisidoro,
Please consider adding this component to HACS, as it would be of great help in keeping this up-to-date.

Thank you very much
Cheers

**Comment by sergioisidoro** [comment]
Hi @makuser Thank you for reaching out! 
I have been thinking about proposing this to the main Home assistant components, but HACS can be a good place to start.

Let me look into this

**Comment by makuser** [comment]
> I have been thinking about proposing this to the main Home assistant components, but HACS can be a good place to start.

Yes exactly, it would be great to publish this via HACS in the meantime.

> Let me look into this

This might be helpful: https://hacs.xyz/docs/publish/start

**Comment by sergioisidoro** [comment]
@makuser just to tell you that there's been some progress on this, since I'm on vacations and had some time to work on it. 

We're still pending the brand and custom wheels PRs to be merged, but the idea would be to make this a default HACS component.

**Comment by sergioisidoro** [comment]
Pull request for HACS is here: https://github.com/hacs/default/pull/861

**Comment by sergioisidoro** [comment]
Seems to have been merged. I'll check that everything is in place, but looks promising!

**Comment by sergioisidoro** [comment]
Could someone confirm that this is working on their HACS setup? :)

**Comment by makuser** [comment]
> Could someone confirm that this is working on their HACS setup? :)

It works perfectly, thank you very much! Great work!
