### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by tctovsli** [ruuvi-friends/ruuvi-hass.io#12]
When installing the module as described, I get an error that the module `simple_ruuvitag` is missing:
`Platform error sensor.ruuvi - No module named 'simple_ruuvitag'`

Steps to reproduce:
1. Copy the contents of custom_components into the folder custom_components
2. Add the documented lines to configuration.yaml
3. Verify configuration/restart Home Assistant

This is on a HassOS installation.

Supervisor version 2020.11.0 
HassOS version 4.17
System version 0.118.2

**Comment by jle1n0** [comment]
The same problem for me...

**Comment by rkallensee** [comment]
I had the same issue initially. For me it worked like this:
- Copy files to `custom_components` (but do not change `configuration.yaml` yet)
- Restart HA (this seems to install the dependencies)
- Add sensor to `configuration.yaml`, configuration should now validate
- Restart HA again
- Sensor should work

**Comment by jle1n0** [comment]
Many thanks @rkallensee, your procedure solved the problem.
