### ISSUE TITLE
Problems starting up the sensor

### ISSUE THREAD

**Issue by peltsippi** [ruuvi-friends/ruuvi-hass.io#2]
Tried to do all prerequisites mentioned here and got this far:

```
Error while setting up hassruuvio platform for sensor
Traceback (most recent call last):
  File "/home/timo/hassio/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/timo/.homeassistant/custom_components/hassruuvio/sensor.py", line 75, in setup_platform
    config.get(CONF_ADAPTER)
  File "/home/timo/.homeassistant/custom_components/hassruuvio/sensor.py", line 101, in __init__
    self.ble_client.setup(mac_addresses=mac_addresses)
AttributeError: 'RuuviTagClient' object has no attribute 'setup'
```

**Comment by sergioisidoro** [comment]
@peltsippi Sorry, I made some restructuring of the `simple-ruuvitag` lib, and I removed the setup method as it made much more sense to do it in __init__. 

This library was installing `simple-ruuvitag` through git, that's why this broke down.

I have already pinned the requirements of the component, so it won't pull the library from git, but rather a specific version from pypi, and fixed the code.

I also improved the logic for handling concurrent updates. 
If you reinstall the component it should be fine.

Also, I think you mentioned that you have a different Bluetooth adaptor. This PR adds support for it https://github.com/ruuvi-friends/ruuvi-hass.io/pull/3

**Comment by peltsippi** [comment]
New PR3 seems to work fine after small modifications to sensor.py. 

I'll just quote the modified rows here because forking seems pretty overkill for this:
`from homeassistant.const import TEMP_CELSIUS, PRESSURE_HPA
....
    'humidity': ['Humidity', '%'],

`
Overall seems to fetch lot less readings but at least for now it seems to be much reliable. I'll probably leave things running at least overinght now that I got that working.

**Comment by sergioisidoro** [comment]
Awesome, glad that it worked. 
And yeah, that was a miss. I will fix that 

One modification I made, which I'm not totally happy with, is that I'm setting the state of a sensor to "none" if a sensor is out of range or does not respond within the timeout of the poll - This is to avoid displaying old information as new. 

However, that sometimes shows data as "Unknown", and it's a bit annoying. 

I have to read up on the topic on how not to update the state if we don't have any new information, but if there's no alternative I might add a setting to avoid resetting the state. 

Tell me also what you think

**Comment by sergioisidoro** [comment]
Sorry, @peltsippi I don't understand what did you encounter with those rows:

Now we import the constants from the `const` from home assistant. Is it a problem related to version? Right now we have:
```
from homeassistant.const import TEMP_CELSIUS, UNIT_PERCENTAGE, PRESSURE_HPA
...

    'temperature': ['Temperature', TEMP_CELSIUS],
    'humidity': ['Humidity', UNIT_PERCENTAGE],
    'pressure': ['Pressure', PRESSURE_HPA],
    'acceleration': ['Acceleration', MILI_G],
    'acceleration_x': ['X Acceleration', MILI_G],
     ...
```

`UNIT_PERCENTAGE` is defined here:
https://github.com/home-assistant/core/blob/dev/homeassistant/const.py#L416

**Comment by sergioisidoro** [comment]
I also just realized how much these changes impact CPU use
<img width="1114" alt="Screenshot 2020-04-12 at 0 24 06" src="https://user-images.githubusercontent.com/5014629/79055229-0dde7000-7c54-11ea-8665-3d7faf7a7936.png">

**Comment by peltsippi** [comment]
> Sorry, @peltsippi I don't understand what did you encounter with those rows:
> 
> Now we import the constants from the `const` from home assistant. Is it a problem related to version? 

The link seems to be for Dev branch, it probably is something that does not yet exist in homeassistant 0.108.3 I am running. At least the integrated updater says it is the latest version.

I'll continue testing and see if I can get this one to freeze. After that I'll collect some statistics from logs and open new issue. I also need to do some research about possible options about what to do if data collection fails for one or two sensors. At the moment it is approximately 22 hour uptime for my testing environment and couple occasional GAP errors have appeared but in general the previous ruuvi-hass was significantly better than older ones and this is at least similar leap forward.
