### ISSUE TITLE
"Cooldown period" required due to new pub sub

### ISSUE THREAD

**Issue by makuser** [ruuvi-friends/ruuvi-hass.io#21]
Now that the data acquisition has been switched to grab every packet being sent by the RuuviTags, we definitely need to introduce some way to slow down the explosion of the database size.

I would suggest to introduce a configurable cooldown period, to only insert a new value after the configured period expires.

I had to downgrade unfortunately, because my database was getting hammered with the tags I am monitoring with a Raspberry Pi, otherwise my SD card would be dead quite soon...

**Comment by sergioisidoro** [comment]
@makuser yeah I had the same issue, and with 4 sensors and a low write speed SD card, I started to have a lag in the history graph.

I needed to change the commit time to mitigate that temporarily. See #19 , but for the time being, please change the `commit_interval` to save your SD card from being hammered.

**Comment by makuser** [comment]
Wonderful, 4ce974412aa75adf39090b4b782a7298dfaa5e04 was exactly what I was looking for! :)
