### ISSUE TITLE
Group all entities of a device as a device

### ISSUE THREAD

**Issue by makuser** [ruuvi-friends/ruuvi-hass.io#37]
As a feature request, I'd really like to have all entities of a configured device to appear as a device in HASS.

This allows for easy low battery level notifications for example and in general just makes it a lot cleaner.

**Comment by sergioisidoro** [comment]
Do you mean that each tag would be one entity, instead of each metric being an entity?

I think that would require quite a bit of refactoring, and I'm wondering if it would even be possible to configure individually which metics to collect. But I can take a look next time I'm doing upgrades. It would also imply a breaking change

**Comment by sergioisidoro** [comment]
So, I investigated this quickly, and it comes at a great expense. 

https://developers.home-assistant.io/docs/core/entity

There's no device class that would fit exactly what Ruuvi does. The closest is the climate / weather, which would not support the accelerometer, battery or signal strength.

So far I still think that having each value as a separate sensor  - https://developers.home-assistant.io/docs/core/entity/sensor - makes more sense. I would be glad to hear your opinion about this given this information.

**Comment by sergioisidoro** [comment]
@makuser Sorry, my mistake. 
Apparently all you need to do is add a `device_info` to the Entity. It might be a relatively easy PR if you want to give it a go

https://developers.home-assistant.io/docs/device_registry_index

**Comment by makuser** [comment]
> Do you mean that each tag would be one entity, instead of each metric being an entity?

No, all entities of a device grouped to appear as a device.

> I think that would require quite a bit of refactoring, and I'm wondering if it would even be possible to configure individually which metics to collect.

No, every entity just needs to have a property that allows HASS to group them together. Eg. MAC address.

> But I can take a look next time I'm doing upgrades.

Thank you! :)

> It would also imply a breaking change

The way you understood it, yeah for sure. The actual request is entirely different though
